Let's import some libraries (numpy and panda)

In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn import datasets
iris = datasets.load_iris()

Let's store the feature matrix in X and response vector in y

In [5]:
X = iris.data
y = iris.target

Let's import the classifier (choose the model/estimator). Ex: KNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier

Let's focus on neighbor = 1

In [11]:
knn = KNeighborsClassifier(n_neighbors=1)

Let's train the model 👌 (fit the estimate)

In [15]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

Let's predict our first data (make prediction)

In [17]:
knn.predict([[3, 5, 4, 2]])

array([2])

In [19]:
print("Predicted target name:", iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


Or, we can do this way,

In [21]:
X_new = np.array([[3, 5, 4, 2]])
print("X_new.shape:", X_new.shape)
mypredict = knn.predict(X_new)
print("Prediction:", mypredict)
print("Predicted target name:", iris['target_names'][mypredict])

X_new.shape: (1, 4)
Prediction: [2]
Predicted target name: ['virginica']


If we want to test two sample (we can just store the arrays in a variable instead for larger case)

In [23]:
knn.predict([[3, 5, 4, 2], [5, 4, 3, 2]])

array([2, 1])

Let's evaluate when we consider neighbor = 3

In [25]:
knn = KNeighborsClassifier(n_neighbors=3)

Let's fit the model for 3

In [27]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [29]:
knn.predict([[3, 5, 4, 2], [5, 4, 3, 2]])

array([1, 1])

Note:
When neighbors = 1, it gives (2, 1)
When neighbors = 3, it gives (1, 1)

Let's try Logistic Regression (learn more...)

In [61]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=110)
lr.fit(X, y)

LogisticRegression(max_iter=110)

In [65]:
lr.predict([[5, 5, 4, 2], [5, 4, 3, 2]])

array([1, 0])