Divide the dataset in two parts
1. Training set
2. Test set
NB: scikit-learn have the function train_test_split for easement

In [1]:
import numpy as np
X, y = np.arange(10).reshape((5, 2)), range (5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
y

range(0, 5)

In [5]:
list(y)

[0, 1, 2, 3, 4]

Above we tried to split training and test set manually, but now we try to do it with functions,
If we don't mention anything it will split train (75%) and test (25%)

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [11]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [13]:
y_train

[1, 4, 2]

In [15]:
X_test

array([[0, 1],
       [6, 7]])

In [17]:
y_test

[0, 3]

In [19]:
train_test_split(y, shuffle=False)
# to not suffle (just testing)

[[0, 1, 2], [3, 4]]

***********

From here we actually work with our iris dataset

***********

In [21]:
# step 01

# load dataset
from sklearn.datasets import load_iris
iris = load_iris()

# set feature and target
X = iris.data
y = iris.target

In [23]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [25]:
# step 02

# import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# from here we will get out train and test value

In [27]:
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [29]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


In [31]:
# if we want our test size 40 and train 60, custome
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [33]:
print(X_test.shape)
print(y_test.shape)

(60, 4)
(60,)


In [35]:
# step 03

# import KNeighborsClassifier where neighbors=3 and fit
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [37]:
print(knn)

KNeighborsClassifier(n_neighbors=3)


In [39]:
# step 04

# predict and extract the accuracy_score
y_pred = knn.predict(X_test)

from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

0.9333333333333333


In [41]:
# if neighbors=5
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.95
