Not to do: To train and evaluate with the same dataset

Let's evaluate with the same training dataset and see what happens

Loading iris datasets

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

Keep the features in X and response in y

In [3]:
X = iris.data
y = iris.target

run knn with neighbour = 3

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

train the model

In [7]:
knn.fit(X, y)

KNeighborsClassifier()

predict the same dataset which we used for training X

In [9]:
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

let's predict first 5 value

In [11]:
knn.predict(X)[0:5]

array([0, 0, 0, 0, 0])

In [13]:
# let's hold the all predict result in y_pred
y_pred = knn.predict(X)
len(y_pred)

150

In [19]:
# let's evaluate score by passing features and response
# here we predict X with known answer y
knn.score(X, y)

0.9666666666666667

In [21]:
# evaluate the accuracy with different method
from sklearn import metrics
print(metrics.accuracy_score(y, y_pred))

0.9666666666666667


As there training and test dataset are same, we can call them training accuracy

In [23]:
# we can also get the accuracy using numpy
import numpy as np
np.mean(y_pred == y)

0.9666666666666667

In [31]:
# what if neighbors=1
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X, y)
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

1.0


In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)